/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './App.tsx',
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--color-brand-50)',
          100: 'var(--color-brand-100)',
          200: 'var(--color-brand-200)',
          300: 'var(--color-brand-300)',
          400: 'var(--color-brand-400)',
          500: 'var(--color-brand-500)',
          600: 'var(--color-brand-600)',
          700: 'var(--color-brand-700)',
          800: 'var(--color-brand-800)',
          900: 'var(--color-brand-900)',
          950: 'var(--color-brand-950)',
          DEFAULT: 'var(--color-brand-500)',
        },
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          950: 'var(--color-accent-950)',
          DEFAULT: 'var(--color-accent-500)',
        },
        canvas: 'var(--color-canvas)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          secondary: 'var(--color-surface-secondary)',
          tertiary: 'var(--color-surface-tertiary)',
        },
        'on-surface': {
          DEFAULT: 'var(--color-on-surface)',
          secondary: 'var(--color-on-surface-secondary)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
        },
      },
      fontFamily: {
        // Define all fonts directly so NativeWind can compile them properly
        satoshi: ['Satoshi', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        jakarta: ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        vietnam: ['Be Vietnam Pro', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        wix: ['Wix Madefor Text', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        figtree: ['Figtree', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        albert: ['Albert Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        epilogue: ['Epilogue', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        manrope: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        public: ['Public Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        space: ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        work: ['Work Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'source-sans': ['Source Sans 3', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        nunito: ['Nunito Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        arimo: ['Arimo', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        hanken: ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        rubik: ['Rubik', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        dm: ['DM Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        ibm: ['IBM Plex Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sora: ['Sora', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        newsreader: ['Newsreader', 'ui-serif', 'serif'],
        noto: ['Noto Serif', 'ui-serif', 'serif'],
        domine: ['Domine', 'ui-serif', 'serif'],
        libre: ['Libre Caslon Text', 'ui-serif', 'serif'],
        garamond: ['EB Garamond', 'ui-serif', 'serif'],
        literata: ['Literata', 'ui-serif', 'serif'],
        'source-serif': ['Source Serif 4', 'ui-serif', 'serif'],
        montserrat: ['Montserrat', 'ui-sans-serif', 'system-ui', 'sans-serif'],

        // Default mappings
        body: ['Satoshi', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Satoshi', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
